@QuizForge_HostAddress = http://localhost:5059
@AccessToken = __SET_ACCESS_TOKEN__

POST {{QuizForge_HostAddress}}/files/presigned-urls/uploads
Content-Type: application/json

{
  "files": [
    {
      "fileName": "pedri_1.jpg",
      "contentType": "image/jpg"
    }
  ]
}

###

POST {{QuizForge_HostAddress}}/documents
Content-Type: application/json

{
  "fileKey": "TIEN_HAI.pdf",
  "sourceType": "pdf_text",
  "isPublic": true,
  "fileHashSha256": "12345678"
}

###

GET {{QuizForge_HostAddress}}/sse/stream
Authorization: Bearer {{AccessToken}}
Accept: text/event-stream

###

POST {{QuizForge_HostAddress}}/sse/self-test
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "eventName": "document.updated",
  "data": {
    "documentId": "12345",
    "status": "processed"
  }
}
