@QuizForge_HostAddress = http://localhost:5059

POST {{QuizForge_HostAddress}}/files/presigned-urls/uploads
Content-Type: application/json

{
  "files": [
    {
      "fileName": "pedri_1.jpg",
      "contentType": "image/jpg"
    }
  ]
}

###

POST {{QuizForge_HostAddress}}/documents
Content-Type: application/json

{
  "fileKey": "TIEN_HAI.pdf",
  "sourceType": "pdf_text",
  "isPublic": true,
  "fileHashSha256": "12345678"
}